apiVersion: v1
kind: Service
metadata:
    name: nginx
    namespace: k8s-hpa-testing
spec:
    selector:
        name: nginx
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80