apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: k8s-hpa-testing
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: nginx
    minReplicas: 3
    maxReplicas: 10